variables:
  IMAGE_NAME: runs-app

stages:
  - build
  - deploy

build:
  image: docker:26.1.3
  stage: build
  services:
    - docker:26.1.3-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker image build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest .
    - docker image push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker image push $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest

deploy:
  stage: deploy
  only:
    - master
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${KUBERNETES_SERVER}" --certificate-authority="${CERTIFICATE_AUTHORITY}" --embed-certs=true
    - kubectl config set-credentials gitlab --token="${TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - helm upgrade running-app ./Helm/running-app-custom-chart --install 
      --set image.repository=${CI_REGISTRY_IMAGE} 
      --set image.name=${IMAGE_NAME} 
      --set image.tag=${CI_COMMIT_SHORT_SHA} 
      --set imagePullSecrets.name=gitlabrunnersecret  
