apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  strategy:
   {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app:  {{.Values.appName }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8}}
      automountServiceAccountToken: false
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
          - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

