apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  # namespace: running-namespace
spec:
  ports:
    - port: {{.Values.service.ports.port}}
      targetPort: 8080
      protocol: TCP
  type: {{ .Values.service.spec.type }}
  selector:
    app: {{ .Values.appName }}
