apiVersion: apps/v1
kind: Deployment
metadata:
  name: running-deployment
spec:
  selector:
    matchLabels:
      app: running-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: running-app
    spec:
      #volumes:
      #  - name: running-volume
      #    persistentVolumeClaim:
      #      claimName: ps-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 500
        runAsGroup: 501
      containers:
      - name: running-app
        image: kozijakinfo/run-app:2.0
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 400m
            memory: 300Mi
          limits:
            cpu: 800m
            memory: 600Mi
              # volumeMounts:
              #- mountPath: /var/tmp/
              #name: running-volume

