apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "standard"
  capacity: 
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: runs-vol
