apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "standard"
  volumeName: persistent-volume
  resources:
    requests:
      storage: 5Gi
